# Generated by Django 6.0.1 on 2026-01-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(help_text='Hero background image URL')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'HomeBanner',
                'verbose_name_plural': 'HomeBanner',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100)),
                ('page_title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=2)),
                ('card_image', models.URLField()),
                ('detail_image', models.URLField()),
                ('overview', models.TextField()),
                ('highlights', models.TextField(help_text='One highlight per line')),
                ('itinerary', models.TextField(help_text='One day per line (Day 1: ..., Day 2: ...)')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
