# Generated by Django 6.0.1 on 2026-01-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homehero',
            name='button1_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homehero',
            name='button1_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homehero',
            name='button2_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homehero',
            name='button2_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homehero',
            name='main_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homehero',
            name='mobile_image',
            field=models.URLField(blank=True, help_text='Mobile hero image', null=True),
        ),
        migrations.AddField(
            model_name='homehero',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homehero',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homehero',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homehero',
            name='image',
            field=models.URLField(blank=True, help_text='Desktop hero image', null=True),
        ),
    ]
