# Generated by Django 6.0.1 on 2026-01-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homehero_button1_link_homehero_button1_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('destinations', 'Destinations Page'), ('carrental', 'Car Rental Page'), ('tempotravel', 'Tempo Travel Page'), ('booking', 'Booking Page')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('desktop_image', models.URLField(blank=True, null=True)),
                ('mobile_image', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Page Banner',
                'verbose_name_plural': 'Page Banners',
            },
        ),
    ]
