# Generated by Django 6.0.1 on 2026-01-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pagebanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeHero',
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='button1_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='button1_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='button2_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='button2_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='main_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagebanner',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
