# Generated by Django 6.0.1 on 2026-01-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_homehero_pagebanner_button1_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBarMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'TopBar Message',
                'verbose_name_plural': 'TopBar Messages',
                'ordering': ['order'],
            },
        ),
    ]
