# Generated by Django 6.0.1 on 2026-01-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_topbarmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topbarmessage',
            options={'ordering': ['order'], 'verbose_name': 'Top Bar Message', 'verbose_name_plural': 'Top Bar Messages'},
        ),
        migrations.AlterField(
            model_name='package',
            name='itinerary',
            field=models.TextField(help_text='One day per line'),
        ),
    ]
