# Generated by Django 6.0.1 on 2026-01-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_topbarmessage_options_alter_package_itinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SubhaYatra', max_length=100)),
                ('meta_title', models.CharField(max_length=60)),
                ('meta_description', models.CharField(max_length=160)),
                ('og_image', models.URLField(blank=True)),
                ('favicon', models.URLField(blank=True)),
            ],
        ),
    ]
